//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_DelayedMessaging p_DelayedMessaging;
        
        public static SteamVR_Input_ActionSet_DelayedMessaging DelayedMessaging
        {
            get
            {
                return SteamVR_Actions.p_DelayedMessaging.GetCopy<SteamVR_Input_ActionSet_DelayedMessaging>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p_DelayedMessaging = ((SteamVR_Input_ActionSet_DelayedMessaging)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_DelayedMessaging>("/actions/DelayedMessaging")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions.DelayedMessaging};
        }
    }
}
