//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_DelayedMessaging : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoystickClick
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_JoystickClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_Grab;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoystickDirection
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_JoystickDirection;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_Menu;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.delayedMessaging_Haptic;
            }
        }
    }
}
